### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by NeuroForLunch** [gr-vt/gr-signal_exciter#18]
What does this do and is this for TX only or RX too?

**Comment by SaikWolf** [comment]
This is an emulation library. It provides a means for those familiar with GNU Radio to create a large set of waveforms quickly/easily. Additionally there's an app for building up large sets of spectrum with multiple signals. Effectively TX only.

Though I haven't been really maintaining it, so until I find a motivation to pick it back up, it is stagnant here.
